/*
WARNING: THIS FILE IS GENERATED BY 'C:/msys64/home/Lex/fteqw/engine/shaders/generatebuiltinsl.c'.
YOU SHOULD NOT EDIT THIS FILE BY HAND
*/

#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/lightmapped",
"!!ver 110\n"
"!!permu FOG\n"
"!!permu BUMP\n"
"!!permu LIGHTSTYLED\n"
"!!permu FULLBRIGHT\n"
"!!permu REFLECTCUBEMASK\n"
"!!permu NOFOG\n"
"!!samps diffuse\n"

"!!samps lightmap\n"
"!!samps =LIGHTSTYLED lightmap1 lightmap2 lightmap3\n"

"!!samps =BUMP normalmap\n"
"!!samps =FULLBRIGHT fullbright\n"

// envmaps only
"!!samps =REFLECTCUBEMASK reflectmask reflectcube\n"

"!!permu FAKESHADOWS\n"
"!!cvardf r_glsl_pcf\n"
"!!samps =FAKESHADOWS shadowmap\n"

"#ifndef ENVTINT\n"
"#define ENVTINT 1.0,1.0,1.0\n"
"#endif\n"

"#ifndef ENVSAT\n"
"#define ENVSAT 1.0,1.0,1.0\n"
"#endif\n"

"#include \"sys/defs.h\"\n"

//ftesurf (P187): $alpha as a compile-time constant.  e_colourident cannot carry
//it -- that is the entity's alpha, one value per entity -- and these materials
//emit a top-level `program` with no pass, so `alphagen const` has nowhere to
//go.  Applied LAST, after any envmap block, because $basealphaenvmapmask reads
//the texture's own alpha and not the material's opacity.
"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"


//ftesurf (P189): the TextureScroll proxy, as a constant velocity in texture
//units per second.  Same idiom as defaultwall.glsl's FLOWV.
"#ifndef SCROLL\n"
"#define SCROLL 0.0,0.0\n"
"#endif\n"


//ftesurf (P251): $seamless_scale -- Source's triplanar projection.
//
//The material stops using its UVs at all and projects the base texture three
//times, down each world axis, blending by the surface normal.  That is what lets
//a mapper drape one cliff texture over a displacement without a seam anywhere.
//
//The math is Valve's, exactly, from the PC branch (the X360 branch additionally
//does max(w-0.3,0) and renormalises; the PC one does not, and does not need to,
//because the weights already sum to 1):
//
//  lightmappedgeneric_vs20.fxc:117   o.SeamlessTexCoord = SEAMLESS_SCALE*worldPos;
//  lightmappedgeneric_vs20.fxc:212   o.vertexColor.xyz  = vNormal * vNormal;
//  common_lightmappedgeneric_fxc.h:103-130
//        vResultBase  = w.x*tex2D(base, coords.zy)
//                     + w.y*tex2D(base, coords.xz)
//                     + w.z*tex2D(base, coords.xy);
//
//Note which coordinate PAIR goes with which weight -- zy, xz, xy, in that order.
//Getting that wrong is invisible on a wall facing an axis and only shows up on a
//slope, which is the only place this material type is ever used.
//
//WORLD space, via m_model, not model space: Source projects from worldPos, so a
//brush entity's texture must stay put when the brush moves rather than travelling
//with it.  On the world model m_model is identity and the multiply folds away.
//
//One thing here is deliberately NOT Valve's.  lightmappedgeneric_ps2_3_x.h:426-428
//skips `albedo *= i.vertexColor` when SEAMLESS, because it has spent the colour
//register on the weights.  This shader carries the weights in their own varying,
//so the material's real $vertexcolor is still its own and the VERTEXCOL multiply
//below stays.
//
//Declared inside the guard: every lightmapped world surface in the game compiles
//this file, and an unguarded pair of varyings would spend two interpolators and a
//matrix multiply on all of them to carry something only four maps ask for.
"#ifdef SEAMLESS\n"
"varying vec3 seam_c; //world position * $seamless_scale\n"
"varying vec3 seam_w; //normal*normal -- the three projection weights, summing to 1\n"
"#endif\n"


//ftesurf (P188): $color / $color2, the per-material tint.  Source multiplies the
//albedo by it; e_colourident cannot carry it because that is the entity's
//colormod, one value for a whole entity, and this is per-material.  Not clamped
//-- values above 1 are authored deliberately.
"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"


"varying vec2 tex_c;\n"

//ftesurf (P232): $vertexcolor / $vertexalpha.  Declared INSIDE the guard, not
//unconditionally, because this shader draws every lightmapped world surface in the
//game and only a displacement painted by the mapper has anything to say here -- an
//always-on varying would spend an interpolator on all of them to carry white.
"#if defined(VERTEXCOL) || defined(VERTEXALPHA)\n"
"varying vec4 vex_color;\n"
"#endif\n"

"varying vec2 lm0;\n"

"#ifdef LIGHTSTYLED\n"
"varying vec2 lm1, lm2, lm3;\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"varying vec4 vtexprojcoord;\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"varying vec3 eyevector;\n"
"varying mat3 invsurface;\n"
"#endif\n"

"#ifdef VERTEX_SHADER\n"
"void lightmapped_init(void)\n"
"{\n"
"lm0 = v_lmcoord;\n"
"#ifdef LIGHTSTYLED\n"
"lm1 = v_lmcoord2;\n"
"lm2 = v_lmcoord3;\n"
"lm3 = v_lmcoord4;\n"
"#endif\n"
"}\n"

"void main ()\n"
"{\n"
"lightmapped_init();\n"
"tex_c = v_texcoord + e_time * vec2(SCROLL);\n"
"gl_Position = ftetransform();\n"
"#if defined(VERTEXCOL) || defined(VERTEXALPHA)\n"
"vex_color = v_colour;\n"
"#endif\n"

"#ifdef SEAMLESS\n"
"seam_c = (m_model * vec4(v_position.xyz, 1.0)).xyz * float(SEAMLESS);\n"
"{\n"
"vec3 wn = (m_model * vec4(v_normal, 0.0)).xyz;\n"
"seam_w = wn * wn; //already sums to 1 for a unit normal; Valve does not normalise on PC\n"
"}\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"invsurface = mat3(v_svector, v_tvector, v_normal);\n"

"vec3 eyeminusvertex = e_eyepos - v_position.xyz;\n"
"eyevector.x = dot(eyeminusvertex, v_svector.xyz);\n"
"eyevector.y = dot(eyeminusvertex, v_tvector.xyz);\n"
"eyevector.z = dot(eyeminusvertex, v_normal.xyz);\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"vtexprojcoord = (l_cubematrix*vec4(v_position.xyz, 1.0));\n"
"#endif\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"

"#ifdef FAKESHADOWS\n"
"#include \"sys/pcf.h\"\n"
"#endif\n"

"#ifdef LIGHTSTYLED\n"
"#define LIGHTMAP0 texture2D(s_lightmap0, lm0).rgb\n"
"#define LIGHTMAP1 texture2D(s_lightmap1, lm1).rgb\n"
"#define LIGHTMAP2 texture2D(s_lightmap2, lm2).rgb\n"
"#define LIGHTMAP3 texture2D(s_lightmap3, lm3).rgb\n"
"#else\n"
"#define LIGHTMAP texture2D(s_lightmap, lm0).rgb \n"
"#endif\n"

"vec3 lightmap_fragment()\n"
"{\n"
"vec3 lightmaps;\n"

"#ifdef LIGHTSTYLED\n"
"lightmaps  = LIGHTMAP0 * e_lmscale[0].rgb;\n"
"lightmaps += LIGHTMAP1 * e_lmscale[1].rgb;\n"
"lightmaps += LIGHTMAP2 * e_lmscale[2].rgb;\n"
"lightmaps += LIGHTMAP3 * e_lmscale[3].rgb;\n"
"#else\n"
"lightmaps  = LIGHTMAP * e_lmscale.rgb;\n"
"#endif\n"
"return lightmaps;\n"
"}\n"

//$seamless_scale sampling, as one macro so the base map and the bump map
//cannot drift apart -- Source projects both through the same
//GetBaseTextureAndNormal call (common_lightmappedgeneric_fxc.h:89-145).
//The zy / xz / xy pairing is Valve's and is load-bearing: swap two of them and
//a wall facing an axis still looks right while every slope goes wrong.
"#ifdef SEAMLESS\n"
"#define SEAMSAMP(s) (seam_w.x*texture2D(s, seam_c.zy) + seam_w.y*texture2D(s, seam_c.xz) + seam_w.z*texture2D(s, seam_c.xy))\n"
"#else\n"
"#define SEAMSAMP(s) texture2D(s, tex_c)\n"
"#endif\n"

"vec3 env_saturation(vec3 rgb, float adjustment) {\n"
"vec3 intensity = vec3(dot(rgb, vec3(0.2126,0.7152,0.0722)));\n"
"return mix(intensity, rgb, adjustment);\n"
"}\n"

"void main (void)\n"
"{\n"
"vec4 diffuse_f;\n"

"diffuse_f = SEAMSAMP(s_diffuse);\n"
"diffuse_f.rgb *= e_colourident.rgb * vec3(COLOR);\n"

"#ifdef MASKLT\n"
"if (diffuse_f.a < float(MASK))\n"
"discard;\n"
"#endif\n"

//ftesurf (P232): the per-vertex tint and opacity the material asked for.
//After the $alphatest discard for the same reason transition.glsl does it
//there -- Source's alpha test reads the texture's alpha, and folding a
//painted fade in first turns the faded end of the ramp into a hole.
"#ifdef VERTEXCOL\n"
"diffuse_f.rgb *= vex_color.rgb;\n"
"#endif\n"
"#ifdef VERTEXALPHA\n"
"diffuse_f.a *= vex_color.a;\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"diffuse_f.rgb *= ShadowmapFilter(s_shadowmap, vtexprojcoord);\n"
"#endif\n"

/* deluxemapping isn't working on Source BSP yet */
"diffuse_f.rgb *= lightmap_fragment();\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
/* We currently only use the normal/bumpmap for cubemap warping. move this block out once we do proper radiosity normalmapping */
"#ifdef BUMP\n"
/* Source's normalmaps are in the DX format where the green channel is flipped */
"vec4 normal_f = SEAMSAMP(s_normalmap);\n"
"normal_f.g = 1.0 - normal_f.g;\n"
"normal_f.rgb = normalize(normal_f.rgb - 0.5);\n"
"#else\n"
"vec4 normal_f = vec4(0.0,0.0,1.0,0.0);\n"
"#endif\n"


"#if defined(ENVFROMMASK)\n"
/* We have a dedicated reflectmask */
"#define refl texture2D(s_reflectmask, tex_c).r\n"
"#else\n"
/* when ENVFROMBASE is set or a normal isn't present, we're getting the reflectivity info from the diffusemap's alpha channel */
"#if defined(ENVFROMBASE) || !defined(BUMP)\n"
"#define refl 1.0 - diffuse_f.a\n"
"#else\n"
/* when ENVFROMNORM is set, we don't invert the refl */
//ftesurf (P251): normal_f.a, not a second texture2D of the same
//sampler.  Identical without $seamless_scale, and with it the
//re-fetch would have used the material's UVs while the normal
//itself came from the triplanar projection -- two different
//texels from one map.  One fetch fewer, too.
"#if defined(ENVFROMNORM)\n"
"#define refl normal_f.a\n"
"#else\n"
"#define refl 1.0 - normal_f.a\n"
"#endif\n"
"#endif\n"
"#endif\n"


"vec3 cube_c = reflect(-eyevector, normal_f.rgb);\n"
"vec3 cube_tint = vec3(ENVTINT);\n"
"vec3 cube_sat = vec3(ENVSAT);\n"
"cube_c = cube_c.x * invsurface[0] + cube_c.y * invsurface[1] + cube_c.z * invsurface[2];\n"
"cube_c = (m_model * vec4(cube_c.xyz, 0.0)).xyz;\n"
"vec3 cube_t = env_saturation(textureCube(s_reflectcube, cube_c).rgb, cube_sat.r);\n"
"cube_t.r *= cube_tint.r;\n"
"cube_t.g *= cube_tint.g;\n"
"cube_t.b *= cube_tint.b;\n"
"diffuse_f.rgb += (cube_t * vec3(refl,refl,refl));\n"
"#endif\n"

"#ifdef FULLBRIGHT\n"
"diffuse_f.rgb += texture2D(s_fullbright, tex_c).rgb * texture2D(s_fullbright, tex_c).a;\n"
"#endif\n"

"diffuse_f.a *= float(ALPHA);\n"

"#ifdef NOFOG\n"
"gl_FragColor = diffuse_f;\n"
"#else\n"
"gl_FragColor = fog4(diffuse_f);\n"
"#endif\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/refract",
"!!ver 110\n"
"!!permu BUMP\n"
"!!samps diffuse\n"
"!!samps =BUMP normalmap\n"
"!!samps refraction=0 dudvmap=1\n"

"#include \"sys/defs.h\"\n"

"varying vec2 tex_c;\n"
"varying mat3 invsurface;\n"
"varying vec4 tf_c;\n"
"varying vec3 eyeminusvertex;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"invsurface[0] = v_svector;\n"
"invsurface[1] = v_tvector;\n"
"invsurface[2] = v_normal;\n"
"tf_c = ftetransform();\n"
"tex_c = v_texcoord;\n"
"gl_Position = tf_c;\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"
"void main ( void )\n"
"{\n"
"vec2 refl_c;\n"
"vec3 refr_f;\n"
"vec3 dudv_f;\n"
"vec4 out_f = vec4( 1.0, 1.0, 1.0, 1.0 );\n"

"dudv_f = ( texture2D( s_dudvmap, tex_c).xyz);\n"
"dudv_f += ( texture2D( s_dudvmap, tex_c).xyz);\n"
"dudv_f -= 1.0 - ( 4.0 / 256.0 );\n"
"dudv_f = normalize( dudv_f );\n"

// Reflection/View coordinates
"refl_c = ( 1.0 + ( tf_c.xy / tf_c.w ) ) * 0.5;\n"

"refr_f = texture2D( s_refraction, refl_c + ( dudv_f.st) ).rgb;\n"
"out_f.rgb = refr_f;\n"
"#ifdef TINTTEXTURE\n"
"out_f.rgb *= texture2D( s_diffuse, tex_c ).rgb;\n"
"#endif\n"

"gl_FragColor = out_f;\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/transition",
"!!ver 110\n"
"!!permu FOG\n"
"!!permu BUMP\n"
"!!permu LIGHTSTYLED\n"
"!!permu REFLECTCUBEMASK\n"
"!!permu UPPERLOWER\n"
"!!samps diffuse\n"
//ftesurf (P187): the second base texture is declared only when the material HAS
//one.  mat_vmt.c used to emit `uppermap "materials/.vtf"` unconditionally, and
//because the blend factor is vertex alpha -- which mod_vbsp.c:2384 leaves at 1.0
//on every non-displacement surface -- mix() then returned that missing texture
//in full and the material's own basetexture was never sampled at all.
"!!samps !NOBLEND upper\n"
//$blendmodulatetexture, carried on the free s_lower slot.  g = where the two
//textures cross over, r = how wide the crossover is.
"!!samps =BLENDMOD lower\n"

"!!samps lightmap\n"
"!!samps =LIGHTSTYLED lightmap1 lightmap2 lightmap3\n"

"!!samps =BUMP normalmap\n"
//ftesurf (P251): $bumpmap2, the SECOND normal map, riding the free s_specular
//slot.  Same reasoning as $blendmodulatetexture on s_lower above: `specularmap`
//(gl_shader.c:3531) is a real sampler keyword that mat_vmt.c emits for nothing
//else, so this costs no engine change and no new interface.  s_fullbright is NOT
//free -- mat_vmt.c:2463-2466 hands it to any material with $selfillum.
"!!samps =BUMP2 specular\n"

// envmaps only
"!!samps =REFLECTCUBEMASK reflectmask reflectcube\n"

"!!permu FAKESHADOWS\n"
"!!cvardf r_glsl_pcf\n"
"!!samps =FAKESHADOWS shadowmap\n"

"#include \"sys/defs.h\"\n"

//ftesurf (P189): the TextureScroll proxy, as a constant velocity in texture
//units per second.  Same idiom as defaultwall.glsl's FLOWV.
"#ifndef SCROLL\n"
"#define SCROLL 0.0,0.0\n"
"#endif\n"


//ftesurf (P188): $color / $color2, the per-material tint.  Source multiplies the
//albedo by it; e_colourident cannot carry it because that is the entity's
//colormod, one value for a whole entity, and this is per-material.  Not clamped
//-- values above 1 are authored deliberately.
"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"


//ftesurf (P187): $alpha, as a compile-time constant.  A Source material's
//opacity is a scalar on the material, not on the entity, so e_colourident (the
//entity's colormod/alpha) cannot carry it -- and this generator emits a
//top-level `program` with no pass, so `alphagen const` has nowhere to live.
//The #define is the same mechanism ENVTINT/ENVSAT already use.
"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"

"varying vec2 tex_c;\n"
"varying vec4 vex_color;\n"

//ftesurf (P251): $seamless_scale, the same triplanar projection lightmapped.glsl
//gained in this patch and for the same reason -- 12 of the library's 26
//$seamless_scale materials are WorldVertexTransition, so implementing it only in
//the other shader would have covered less than half of them.  Valve's PC math,
//from lightmappedgeneric_vs20.fxc:117/:212 and
//common_lightmappedgeneric_fxc.h:103-130; the full derivation is written out in
//lightmapped.glsl rather than repeated here.
"#ifdef SEAMLESS\n"
"varying vec3 seam_c; //world position * $seamless_scale\n"
"varying vec3 seam_w; //normal*normal, summing to 1\n"
"#endif\n"

"varying vec2 lm0;\n"

"#ifdef LIGHTSTYLED\n"
"varying vec2 lm1, lm2, lm3;\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"varying vec4 vtexprojcoord;\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"varying vec3 eyevector;\n"
"varying mat3 invsurface;\n"
"#endif\n"

"#ifdef VERTEX_SHADER\n"
"void lightmapped_init(void)\n"
"{\n"
"lm0 = v_lmcoord;\n"
"#ifdef LIGHTSTYLED\n"
"lm1 = v_lmcoord2;\n"
"lm2 = v_lmcoord3;\n"
"lm3 = v_lmcoord4;\n"
"#endif\n"
"}\n"

"void main ()\n"
"{\n"
"lightmapped_init();\n"
"tex_c = v_texcoord + e_time * vec2(SCROLL);\n"
"gl_Position = ftetransform();\n"
"vex_color = v_colour;\n"

"#ifdef SEAMLESS\n"
"seam_c = (m_model * vec4(v_position.xyz, 1.0)).xyz * float(SEAMLESS);\n"
"{\n"
"vec3 wn = (m_model * vec4(v_normal, 0.0)).xyz;\n"
"seam_w = wn * wn;\n"
"}\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"invsurface = mat3(v_svector, v_tvector, v_normal);\n"

"vec3 eyeminusvertex = e_eyepos - v_position.xyz;\n"
"eyevector.x = dot(eyeminusvertex, v_svector.xyz);\n"
"eyevector.y = dot(eyeminusvertex, v_tvector.xyz);\n"
"eyevector.z = dot(eyeminusvertex, v_normal.xyz);\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"vtexprojcoord = (l_cubematrix*vec4(v_position.xyz, 1.0));\n"
"#endif\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"

"#ifdef FAKESHADOWS\n"
"#include \"sys/pcf.h\"\n"
"#endif\n"

"#ifdef LIGHTSTYLED\n"
"#define LIGHTMAP0 texture2D(s_lightmap0, lm0).rgb\n"
"#define LIGHTMAP1 texture2D(s_lightmap1, lm1).rgb\n"
"#define LIGHTMAP2 texture2D(s_lightmap2, lm2).rgb\n"
"#define LIGHTMAP3 texture2D(s_lightmap3, lm3).rgb\n"
"#else\n"
"#define LIGHTMAP texture2D(s_lightmap, lm0).rgb \n"
"#endif\n"

//$seamless_scale sampling -- see lightmapped.glsl for the derivation.  Applied
//to the base, the SECOND base and both normal maps, because Source projects
//all of them through the same GetBaseTextureAndNormal call.  NOT applied to
//$blendmodulatetexture: Source samples that from lightmapTexCoord3.zw, a
//separate coordinate set it never puts through the projection
//(lightmappedgeneric_ps2_3_x.h:321).
"#ifdef SEAMLESS\n"
"#define SEAMSAMP(s) (seam_w.x*texture2D(s, seam_c.zy) + seam_w.y*texture2D(s, seam_c.xz) + seam_w.z*texture2D(s, seam_c.xy))\n"
"#else\n"
"#define SEAMSAMP(s) texture2D(s, tex_c)\n"
"#endif\n"

"vec3 lightmap_fragment()\n"
"{\n"
"vec3 lightmaps;\n"

"#ifdef LIGHTSTYLED\n"
"lightmaps  = LIGHTMAP0 * e_lmscale[0].rgb;\n"
"lightmaps += LIGHTMAP1 * e_lmscale[1].rgb;\n"
"lightmaps += LIGHTMAP2 * e_lmscale[2].rgb;\n"
"lightmaps += LIGHTMAP3 * e_lmscale[3].rgb;\n"
"#else\n"
"lightmaps  = LIGHTMAP * e_lmscale.rgb;\n"
"#endif\n"

/* the light we're getting is always too bright */
"lightmaps *= 0.75;\n"

/* clamp at 1.5 */
"if (lightmaps.r > 1.5)\n"
"lightmaps.r = 1.5;\n"
"if (lightmaps.g > 1.5)\n"
"lightmaps.g = 1.5;\n"
"if (lightmaps.b > 1.5)\n"
"lightmaps.b = 1.5;\n"

"return lightmaps;\n"
"}\n"

"void main (void)\n"
"{\n"
"vec4 diffuse_f;\n"

// ftesurf (P187): this used to be
//     diffuse_f.rgb = mix(s_diffuse, s_upper, vex_color.a);
//     diffuse_f.a = 1.0;
// and both lines were wrong.
//
// THE ALPHA.  Forcing it to 1.0 meant that mat_vmt.c's
// `progblendfunc src_alpha one_minus_src_alpha` -- which it emits for
// every $translucent material -- always blended with src_alpha == 1,
// i.e. fully opaque.  The surface therefore looked solid while still
// paying the entire cost of transparency: a blend cannot write depth,
// so it is sorted back-to-front and everything behind it is drawn
// anyway.  That is both "the smoke is solid" and part of "the map runs
// at 30fps", from one line.  lightmapped.glsl never did this, which is
// why an ordinary $translucent LightmappedGeneric has always blended
// correctly and only this shader was reported broken.
//
// THE MIX.  See the !!samps note above: with no second texture the mix
// returned a missing image in full.  #NOBLEND is now emitted for
// exactly that case and the sampler is not even declared.
"vec4 base_f = SEAMSAMP(s_diffuse);\n"

"#ifdef NOBLEND\n"
"diffuse_f = base_f;\n"
"#else\n"
"float blend = vex_color.a;\n"
"#ifdef BLENDMOD\n"
// Source's shaped transition.  The modulate map's green channel is the
// midpoint and its red channel the half-width, so the crossover happens
// over [g-r, g+r] instead of linearly across the whole range -- which is
// what makes a blend read as gravel through tarmac rather than as a fade.
// smoothstep is undefined when its edges are equal, and r == 0 is a
// legitimate authoring choice meaning "hard edge", so that case is a step.
"vec4 mod_f = texture2D(s_lower, tex_c);\n"
"float lo = clamp(mod_f.g - mod_f.r, 0.0, 1.0);\n"
"float hi = clamp(mod_f.g + mod_f.r, 0.0, 1.0);\n"
"blend = (hi > lo) ? smoothstep(lo, hi, blend) : step(lo, blend);\n"
"#endif\n"
"diffuse_f = mix(base_f, SEAMSAMP(s_upper), blend);\n"
"#endif\n"

//$alphatest.  mat_vmt.c has always emitted #MASK/#MASKLT for this
//material type and this shader has never read it, so an alpha-masked
//transition surface came out as a solid rectangle.
"#ifdef MASKLT\n"
"if (diffuse_f.a < float(MASK))\n"
"discard;\n"
"#endif\n"

//ftesurf (P232): $vertexcolor / $vertexalpha, the per-vertex tint and opacity.
//
//AFTER the $alphatest discard on purpose.  Source's alpha test reads the
//TEXTURE's alpha, so a region the mapper painted to fade has to fade -- if the
//vertex value were folded in first, the faded end of the ramp would fall under
//MASK and be cut out instead, which is a hole rather than a gradient.
//
//In the blended path vex_color.a is ALSO the mix factor, so a material asking
//for both would be spending one channel twice.  No such material exists: see
//the census in mat_vmt.c beside the #VERTEXALPHA emit.
"#ifdef VERTEXCOL\n"
"diffuse_f.rgb *= vex_color.rgb;\n"
"#endif\n"
"#ifdef VERTEXALPHA\n"
"diffuse_f.a *= vex_color.a;\n"
"#endif\n"

"diffuse_f.rgb *= vec3(COLOR);\n"

/* deluxemapping isn't working on Source BSP yet, FIXME */
"diffuse_f.rgb *= lightmap_fragment();\n"

"#ifdef FAKESHADOWS\n"
"diffuse_f.rgb *= ShadowmapFilter(s_shadowmap, vtexprojcoord);\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
/* We currently only use the normal/bumpmap for cubemap warping. move this block out once we do proper radiosity normalmapping */
"#ifdef BUMP\n"
/* Source's normalmaps are in the DX format where the green channel is flipped */
"vec4 normal_f = SEAMSAMP(s_normalmap);\n"
//ftesurf (P251): $bumpmap2 -- the second normal map, blended by the SAME
//factor as the two base textures.  Valve, lightmappedgeneric_ps2_3_x.h:378-382:
//
//	vNormal.xyz = lerp( vNormal.xyz, vNormal2.xyz, blendfactor );
//
//Three details worth having right, all of them from those lines:
//  - the factor is `blendfactor`, the one the diffuse already used, INCLUDING
//    the $blendmodulatetexture reshaping at :321-331.  So this must sit after
//    `blend` has been through the BLENDMOD smoothstep, and it does.
//  - it is a lerp of the two normals, NOT of the raw texels and NOT
//    renormalised afterwards.  Doing it before the DX green flip and the
//    -0.5 unpack keeps that true, because both are affine in the texel.
//  - same texture coordinates as $bumpmap (the separate-coords case is
//    BUMPMASK, which Source itself excludes from this path).
//
//#BUMP2 is only emitted when the material has a $basetexture2, so `blend`
//is always in scope here -- with #NOBLEND there is nothing to blend toward
//and mat_vmt.c does not ask for this permutation.
"#ifdef BUMP2\n"
"normal_f = mix(normal_f, SEAMSAMP(s_specular), blend);\n"
"#endif\n"
"normal_f.g = 1.0 - normal_f.g;\n"
"normal_f.rgb = normalize(normal_f.rgb - 0.5);\n"
"#else\n"
"vec4 normal_f = vec4(0.0,0.0,1.0,0.0);\n"
"#endif\n"

"#if defined(ENVFROMMASK)\n"
/* We have a dedicated reflectmask */
"#define refl texture2D(s_reflectmask, tex_c).r\n"
"#else\n"
/* when ENVFROMBASE is set or a normal isn't present, we're getting the reflectivity info from the diffusemap's alpha channel */
"#if defined(ENVFROMBASE) || !defined(BUMP)\n"
"#define refl 1.0 - diffuse_f.a\n"
"#else\n"
/* when ENVFROMNORM is set, we don't invert the refl */
"#if defined(ENVFROMNORM)\n"
//ftesurf (P251): normal_f.a rather than a second fetch of the same
//sampler -- identical before this patch, and now the only version
//that stays correct, since normal_f may be a $seamless_scale
//projection and/or a $bumpmap2 blend that a plain tex_c re-fetch
//would not reproduce.
"#define refl normal_f.a\n"
"#else\n"
"#define refl 1.0 - normal_f.a\n"
"#endif\n"
"#endif\n"
"#endif\n"

"vec3 cube_c = reflect(normalize(-eyevector), normal_f.rgb);\n"
"cube_c = cube_c.x * invsurface[0] + cube_c.y * invsurface[1] + cube_c.z * invsurface[2];\n"
"cube_c = (m_model * vec4(cube_c.xyz, 0.0)).xyz;\n"
"diffuse_f.rgb += (textureCube(s_reflectcube, cube_c).rgb * vec3(refl,refl,refl));\n"
"#endif\n"

//AFTER the envmap block on purpose: `refl` above is 1.0 - diffuse_f.a,
//and Source's $basealphaenvmapmask reads the TEXTURE's alpha, not the
//material's opacity.  (Note that with the old hardcoded a = 1.0 that
//refl was a constant zero, so #ENVFROMBASE on a transition material has
//never reflected anything until now.)
"diffuse_f.a *= float(ALPHA);\n"

"#ifdef NOFOG\n"
"gl_FragColor = diffuse_f;\n"
"#else\n"
"gl_FragColor = fog4(diffuse_f);\n"
"#endif\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/unlit",
"!!ver 110\n"
"!!permu FOG\n"
"!!samps diffuse\n"

"#include \"sys/defs.h\"\n"

//ftesurf (P187): $alpha as a compile-time constant.  e_colourident cannot carry
//it -- that is the entity's alpha, one value per entity -- and these materials
//emit a top-level `program` with no pass, so `alphagen const` has nowhere to
//go.  Applied LAST, after any envmap block, because $basealphaenvmapmask reads
//the texture's own alpha and not the material's opacity.
"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"


//ftesurf (P189): the TextureScroll proxy, as a constant velocity in texture
//units per second.  Same idiom as defaultwall.glsl's FLOWV.
"#ifndef SCROLL\n"
"#define SCROLL 0.0,0.0\n"
"#endif\n"


//ftesurf (P188): $color / $color2, the per-material tint.  Source multiplies the
//albedo by it; e_colourident cannot carry it because that is the entity's
//colormod, one value for a whole entity, and this is per-material.  Not clamped
//-- values above 1 are authored deliberately.
"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"

"#include \"sys/fog.h\"\n"

"varying vec2 tex_c;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"tex_c = v_texcoord + e_time * vec2(SCROLL);\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"void main ()\n"
"{\n"
"vec4 diffuse_f = texture2D( s_diffuse, tex_c );\n"
"diffuse_f.rgb *= vec3(COLOR);\n"

"#ifdef MASKLT\n"
"if (diffuse_f.a < float(MASK))\n"
"discard;\n"
"#endif\n"

"diffuse_f.a *= float(ALPHA);\n"
"gl_FragColor = fog4( diffuse_f );\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/vertexlit",
"!!ver 100 150\n"
"!!permu FRAMEBLEND\n"
"!!permu BUMP\n"
"!!permu FOG\n"
"!!permu NOFOG\n"
"!!permu SKELETAL\n"
"!!permu FULLBRIGHT\n"
"!!permu AMBIENTCUBE\n"
"!!permu VC   // FTESurf Patch 259: VRAD's own per-vertex bake for THIS prop instance (sp_N.vhv), as a multiplier over `light`\n"
"!!permu REFLECTCUBEMASK\n"
"!!samps diffuse\n"
"!!samps =BUMP normalmap\n"
"!!samps =FULLBRIGHT fullbright\n"
"!!samps rtenvsphere:2D=0\n"
"!!permu FAKESHADOWS\n"
"!!cvardf r_glsl_pcf\n"
"!!cvardf r_glsl_rtenvsphere\n"
"!!samps =FAKESHADOWS shadowmap\n"

// envmaps only
"!!samps =REFLECTCUBEMASK reflectmask reflectcube\n"
"!!cvardf r_skipDiffuse\n"

"#include \"sys/defs.h\"\n"

//ftesurf (P187): $alpha as a compile-time constant.  e_colourident cannot carry
//it -- that is the entity's alpha, one value per entity -- and these materials
//emit a top-level `program` with no pass, so `alphagen const` has nowhere to
//go.  Applied LAST, after any envmap block, because $basealphaenvmapmask reads
//the texture's own alpha and not the material's opacity.
"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"


//ftesurf (P189): the TextureScroll proxy, as a constant velocity in texture
//units per second.  Same idiom as defaultwall.glsl's FLOWV.
"#ifndef SCROLL\n"
"#define SCROLL 0.0,0.0\n"
"#endif\n"


//ftesurf (P188): $color / $color2, the per-material tint.  Source multiplies the
//albedo by it; e_colourident cannot carry it because that is the entity's
//colormod, one value for a whole entity, and this is per-material.  Not clamped
//-- values above 1 are authored deliberately.
"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"


"varying vec2 tex_c;\n"
"varying vec3 norm;\n"
"varying vec4 light;\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"varying vec3 eyevector;\n"
"varying mat3 invsurface;\n"

"#endif\n"

"#ifndef ENVTINT\n"
"#define ENVTINT 1.0,1.0,1.0\n"
"#endif\n"

"#ifndef ENVSAT\n"
"#define ENVSAT 1.0\n"
"#endif\n"


"#ifdef FAKESHADOWS\n"
"varying vec4 vtexprojcoord;\n"
"#endif\n"

"#ifdef VERTEX_SHADER\n"
"#include \"sys/skeletal.h\"\n"

"float lambert(vec3 normal, vec3 dir)\n"
"{\n"
"return dot(normal, dir);\n"
"}\n"

"float halflambert(vec3 normal, vec3 dir)\n"
"{\n"
"return (dot(normal, dir) * 0.5) + 0.5;\n"
"}\n"

"void main (void)\n"
"{\n"
"vec3 n, s, t, w;\n"
"tex_c = v_texcoord + e_time * vec2(SCROLL);\n"
"gl_Position = skeletaltransform_wnst(w,n,s,t);\n"
"norm = n = normalize(n);\n"
"s = normalize(s);\n"
"t = normalize(t);\n"
"light.rgba = vec4(e_light_ambient, 1.0);\n"

"#ifdef AMBIENTCUBE\n"
//no specular effect here. use rtlights for that.
"vec3 nn = norm*norm; //FIXME: should be worldspace normal.\n"
"light.rgb = nn.x * e_light_ambientcube[(norm.x<0.0)?1:0] +\n"
"nn.y * e_light_ambientcube[(norm.y<0.0)?3:2] +\n"
"nn.z * e_light_ambientcube[(norm.z<0.0)?5:4];\n"
"#else\n"
"#ifdef HALFLAMBERT\n"
"light.rgb += max(0.0,halflambert(n,e_light_dir)) * e_light_mul;\n"
"#else\n"
"light.rgb += max(0.0,dot(n,e_light_dir)) * e_light_mul;\n"
"#endif\n"
"#endif\n"

//FTESurf Patch 259.  v_colour carries VRAD's OWN per-vertex answer for this
//exact prop instance, read out of the map's sp_N.vhv and normalised so its
//brightest vertex is exactly 1.0 -- the gain that normalisation removed was
//folded back into e_light_ambient, so this multiply restores the absolute
//value rather than darkening the model.
//
//Greyscale on purpose (see VBSP_LoadPropBakedLight): light.rgb already
//carries the prop's colour from the same bake's mean, so a per-channel
//multiplier here would tint it twice.  This carries only where the light
//falls -- which is the whole difference between a hedge and a green blob.
//
//Multiplied over the WHOLE of light, ambient and directional alike, the same
//way defaultskin.glsl:115 does it.  In Patch 259's mode the directional half
//is zero anyway: VRAD already integrated N.L into these numbers, so applying
//ours on top would shade the prop twice.
//
//And the comment is // rather than /* */ deliberately: generatebuiltinsl
//emits a line beginning /* raw and then QUOTES the lines after it, so a
//multi-line block comment produces an unterminated C comment in
//mat_vmt_progs.h and the plugin will not compile.  Every other comment in
//these files is either // or a /* */ that opens and closes on one line.
"#ifdef VC\n"
"light.rgb *= v_colour.rgb;\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"
"invsurface = mat3(s, t, n);\n"

"vec3 eyeminusvertex = e_eyepos - w.xyz;\n"
"eyevector.x = dot(eyeminusvertex, s.xyz);\n"
"eyevector.y = dot(eyeminusvertex, t.xyz);\n"
"eyevector.z = dot(eyeminusvertex, n.xyz);\n"
"#endif\n"

"#ifdef FAKESHADOWS\n"
"vtexprojcoord = (l_cubematrix*vec4(w.xyz, 1.0));\n"
"#endif\n"
"}\n"
"#endif\n"


"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"
"#include \"sys/pcf.h\"\n"

"vec3 env_saturation(vec3 rgb, float adjustment) {\n"
"vec3 intensity = vec3(dot(rgb, vec3(0.2126,0.7152,0.0722)));\n"
"return mix(intensity, rgb, adjustment);\n"
"}\n"

"void main (void)\n"
"{\n"
"vec4 diffuse_f = texture2D(s_diffuse, tex_c);\n"
"diffuse_f.rgb *= vec3(COLOR);\n"

"#ifdef MASKLT\n"
"if (diffuse_f.a < float(MASK))\n"
"discard;\n"
"#endif\n"

/* Normal/Bumpmap Shenanigans */
"#ifdef BUMP\n"
/* Source's normalmaps are in the DX format where the green channel is flipped */
"vec3 normal_f = texture2D(s_normalmap, tex_c).rgb;\n"
"normal_f.g = 1.0 - normal_f.g;\n"
"normal_f = normalize(normal_f.rgb - 0.5);\n"
"#else\n"
"vec3 normal_f = vec3(0.0,0.0,1.0);\n"
"#endif\n"

/* CUBEMAPS ONLY */
"#ifdef REFLECTCUBEMASK\n"

"#if defined(ENVFROMMASK)\n"
/* We have a dedicated reflectmask */
"#define refl texture2D(s_reflectmask, tex_c).r\n"
"#else\n"
/* when ENVFROMBASE is set or a normal isn't present, we're getting the reflectivity info from the diffusemap's alpha channel */
"#if defined(ENVFROMBASE) || !defined(BUMP)\n"
"#define refl 1.0 - diffuse_f.a\n"
"#else\n"
/* when ENVFROMNORM is set, we don't invert the refl */
"#if defined(ENVFROMNORM)\n"
"#define refl texture2D(s_normalmap, tex_c).a\n"
"#else\n"
"#define refl 1.0 - texture2D(s_normalmap, tex_c).a\n"
"#endif\n"
"#endif\n"
"#endif\n"

"vec3 cube_tint = vec3(ENVTINT);\n"
"vec3 cube_sat = vec3(ENVSAT);\n"

"#if r_glsl_rtenvsphere == 1\n"
"vec3 r = reflect(normalize(-eyevector), normal_f.rgb);\n"
"vec2 sphereCoord = 0.5 + r.xy * 0.5;\n"
"vec3 cube_t = env_saturation(texture2D(s_rtenvsphere, sphereCoord).rgb * 0.5, cube_sat.r);\n"
"#else\n"
"vec3 cube_c = reflect(-eyevector, normal_f.rgb);\n"
"cube_c = cube_c.x * invsurface[0] + cube_c.y * invsurface[1] + cube_c.z * invsurface[2];\n"
"cube_c = (m_model * vec4(cube_c.xyz, 0.0)).xyz;\n"
"vec3 cube_t = env_saturation(textureCube(s_reflectcube, cube_c).rgb, cube_sat.r);\n"
"#endif\n"

"cube_t.r *= cube_tint.r;\n"
"cube_t.g *= cube_tint.g;\n"
"cube_t.b *= cube_tint.b;\n"

"diffuse_f.rgb += (cube_t * vec3(refl,refl,refl));\n"
"#endif\n"

"diffuse_f.rgb *= light.rgb * e_colourident.rgb;\n"

"#ifdef FAKESHADOWS\n"
"diffuse_f.rgb *= ShadowmapFilter(s_shadowmap, vtexprojcoord);\n"
"#endif\n"

"#ifdef FULLBRIGHT\n"
"diffuse_f.rgb += texture2D(s_fullbright, tex_c).rgb * texture2D(s_fullbright, tex_c).a;\n"
"#endif\n"


"diffuse_f.a *= float(ALPHA);\n"

//FTESurf Patch 255: was #if 1, so the fog branch was dead and EVERY Source
//prop drew unfogged. NOFOG was declared above and never used; animated,
//lightmapped and transition all spell this test the same way. See P255.
"#ifdef NOFOG\n"
"gl_FragColor = diffuse_f;\n"
"#else\n"
"gl_FragColor = fog4(diffuse_f);\n"
"#endif\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/water",
"!!cvardf r_glsl_turbscale_reflect=1 //simpler scaler\n"
"!!cvardf r_glsl_turbscale_refract=1 //simpler scaler\n"
"!!permu REFLECTCUBEMASK\n"
"!!samps diffuse normalmap\n"
"!!samps refract=0 //always present\n"
"!!samps reflect=1\n"
"!!samps =REFLECTCUBEMASK reflectcube\n"
"!!permu FOG\n"

"#include \"sys/defs.h\"\n"

//modifier: REFLECT		(s_t2 is a reflection instead of diffusemap)
//modifier: STRENGTH_REFL	(distortion strength - 0.1 = fairly gentle, 0.2 = big waves)
//modifier: STRENGTH_REFL	(distortion strength - 0.1 = fairly gentle, 0.2 = big waves)
//modifier: FRESNEL_EXP	(5=water)
//modifier: TXSCALE		(wave size - 0.2)
//modifier: RIPPLEMAP		(s_t3 contains a ripplemap
//modifier: TINT_REFR		(some colour value)
//modifier: TINT_REFL		(some colour value)
//modifier: ALPHA		(mix in the normal water texture over the top)
//modifier: USEMODS		(use single-texture scrolling via tcmods - note, also forces the engine to actually use tcmod etc)

//a few notes on DP compat:
//'dpwater' makes numerous assumptions about DP internals
//by default there is a single pass that uses the pass's normal tcmods
//the fresnel has a user-supplied min+max rather than an exponent
//both parts are tinted individually
//if alpha is enabled, the regular water texture is blended over the top, again using the same crappy tcmods...

//legacy crap
"#ifndef FRESNEL\n"
"#define FRESNEL 5.0\n"
"#endif\n"
"#ifndef TINT\n"
"#define TINT 0.7,0.8,0.7\n"
"#endif\n"
"#ifndef STRENGTH\n"
"#define STRENGTH 0.25\n"
"#endif\n"
"#ifndef TXSCALE\n"
"#define TXSCALE 1\n"
"#endif\n"

//current values (referring to legacy defaults where needed)
"#ifndef FRESNEL_EXP\n"
"#define FRESNEL_EXP 5.0\n"
"#endif\n"
"#ifndef FRESNEL_MIN\n"
"#define FRESNEL_MIN 0.0\n"
"#endif\n"
"#ifndef FRESNEL_RANGE\n"
"#define FRESNEL_RANGE 1.0\n"
"#endif\n"
"#ifndef STRENGTH_REFL\n"
"#define STRENGTH_REFL STRENGTH\n"
"#endif\n"
"#ifndef STRENGTH_REFR\n"
"#define STRENGTH_REFR STRENGTH\n"
"#endif\n"
"#ifndef TXSCALE1\n"
"#define TXSCALE1 TXSCALE\n"
"#endif\n"
"#ifndef TXSCALE2\n"
"#define TXSCALE2 TXSCALE\n"
"#endif\n"
"#ifndef TINT_REFR\n"
"#define TINT_REFR TINT\n"
"#endif\n"
"#ifndef TINT_REFL\n"
"#define TINT_REFL 1.0,1.0,1.0\n"
"#endif\n"
"#ifndef FOGTINT\n"
"#define FOGTINT 0.2,0.3,0.2\n"
"#endif\n"

"varying vec2 tc;\n"
"varying vec4 tf;\n"
"varying vec3 norm;\n"
"varying vec3 eye;\n"

"#ifdef VERTEX_SHADER\n"
"void main (void)\n"
"{\n"
"tc = v_texcoord.st;\n"
"tf = ftetransform();\n"
"norm = v_normal;\n"
"eye = e_eyepos - v_position.xyz;\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"


"void main (void)\n"
"{\n"
"vec2 stc; //screen tex coords\n"
"vec2 ntc; //normalmap/diffuse tex coords\n"
"vec3 n, refr, refl;\n"
"float fres;\n"
"float depth;\n"
"stc = (1.0 + (tf.xy / tf.w)) * 0.5;\n"
//hack the texture coords slightly so that there are less obvious gaps
"stc.t -= 1.5*norm.z/1080.0;\n"

"#if 0//def USEMODS\n"
"ntc = tc;\n"
"n = texture2D(s_normalmap, ntc).xyz - 0.5;\n"
"#else\n"
//apply q1-style warp, just for kicks
"ntc.s = tc.s + sin(tc.t+e_time)*0.125;\n"
"ntc.t = tc.t + sin(tc.s+e_time)*0.125;\n"

//generate the two wave patterns from the normalmap
"n = (texture2D(s_normalmap, vec2(TXSCALE1)*tc + vec2(e_time*0.1, 0.0)).xyz);\n"
"n += (texture2D(s_normalmap, vec2(TXSCALE2)*tc - vec2(0, e_time*0.097)).xyz);\n"
"n -= 1.0 - 4.0/256.0;\n"
"#endif\n"

"#ifdef RIPPLEMAP\n"
"n += texture2D(s_ripplemap, stc).rgb*3.0;\n"
"#endif\n"
"n = normalize(n);\n"

//the fresnel term decides how transparent the water should be
"fres = pow(1.0-abs(dot(n, normalize(eye))), float(FRESNEL_EXP)) * float(FRESNEL_RANGE) + float(FRESNEL_MIN);\n"

"#ifdef DEPTH\n"
"float far = #include \"cvar/gl_maxdist\";\n"
"float near = #include \"cvar/gl_mindist\";\n"
//get depth value at the surface
"float sdepth = gl_FragCoord.z;\n"
"sdepth = (2.0*near) / (far + near - sdepth * (far - near));\n"
"sdepth = mix(near, far, sdepth);\n"

//get depth value at the ground beyond the surface.
"float gdepth = texture2D(s_refractdepth, stc).x;\n"
"gdepth = (2.0*near) / (far + near - gdepth * (far - near));\n"
"if (gdepth >= 0.5)\n"
"{\n"
"gdepth = sdepth;\n"
"depth = 0.0;\n"
"}\n"
"else\n"
"{\n"
"gdepth = mix(near, far, gdepth);\n"
"depth = gdepth - sdepth;\n"
"}\n"

//reduce the normals in shallow water (near walls, reduces the pain of linear sampling)
"if (depth < 100.0)\n"
"n *= depth/100.0;\n"
"#else\n"
"depth = 1.0;\n"
"#endif \n"


//refraction image (and water fog, if possible)
"refr = texture2D(s_refract, stc + n.st*float(STRENGTH_REFR)*float(r_glsl_turbscale_refract)).rgb * vec3(TINT_REFR);\n"
"#ifdef DEPTH\n"
"refr = mix(refr, vec3(FOGTINT), min(depth/4096.0, 1.0));\n"
"#endif\n"

"#ifdef LQWATER\n"
"refl = textureCube(s_reflectcube, n).rgb;// * vec3(TINT_REFL);\n"
"#else\n"
"refl = texture2D(s_reflect, stc - n.st*float(STRENGTH_REFL)*float(r_glsl_turbscale_reflect)).rgb * vec3(TINT_REFL);\n"
"#endif\n"

//interplate by fresnel
"refr = mix(refr, refl, fres);\n"

"#ifdef ALPHA\n"
"vec4 ts = texture2D(s_diffuse, ntc);\n"
"vec4 surf = fog4blend(vec4(ts.rgb, float(ALPHA)*ts.a));\n"
"refr = mix(refr, surf.rgb, surf.a);\n"
"#else\n"
"refr = fog3(refr); \n"
"#endif\n"

//done
"gl_FragColor = vec4(refr, 1.0);\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/rt",
"!!ver 110\n"
"!!permu FOG\n"
"!!samps diffuse=0\n"

"#include \"sys/defs.h\"\n"
"#include \"sys/fog.h\"\n"

"varying vec2 tex_c;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"tex_c = v_texcoord;\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"void main ()\n"
"{\n"
"vec4 diffuse_f = texture2D( s_diffuse, fract(tex_c) );\n"
"gl_FragColor = fog4( diffuse_f );\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/flatdither",
"!!ver 110\n"
"!!fixed\n"
"!!permu FOG\n"
"!!samps flat=0\n"

// FTESurf Patch 151 -- ordered-dither stand-in for Source's expensive surfaces.
//
// WHY A DITHER RATHER THAN A BLEND.  Source water compiles to $refraction +
// $reflection and Source glass to $currentrender; all three are RENDER TARGETS,
// and the backend fills them by rendering the scene again, per batch.  Turning
// them off still left a translucent sheet, which is cheap to fill but is NOT
// free: a blended surface cannot write depth, so it has to be sorted back to
// front and everything behind it is drawn whether or not you can see it.
//
// An ordered dither is opaque geometry with a discard.  No blend, no sort, no
// framebuffer copy, no render target, and it WRITES DEPTH -- so the geometry
// behind it is z-rejected instead of overdrawn.  It is strictly cheaper than
// the translucent version it replaces, and it is a look you choose rather than
// a degradation you tolerate.
//
// The colour and the coverage are the material's own: mat_vmt.c feeds them in
// through the pass's rgbgen/alphagen const, which arrive here as v_colour, so
// each material still looks like itself and no shader permutation is spent on
// them.
//
// FTESurf Patch 159 -- `!!fixed` IS LOAD-BEARING AND BUILD 12 SHIPPED WITHOUT IT.
//
// GenerateColourMods -- the only thing that ever evaluates an rgbgen or an
// alphagen -- runs from gl_backend.c:4354 under `if (p->calcgens)`, and
// calcgens is set by exactly two things: `!!fixed` at the top of the GLSL, or
// `#usemods` in the program name (gl_shader.c:1831-1834, 2247-2248).  This had
// neither, so v_colour was never written for this program: the pass inherited
// whatever colour array the previous draw happened to leave bound.
//
// That is the whole of "hl2_water 3 makes the water a white dithered surface"
// and "hl2_dither_alpha does nothing at hl2_water 3".  The colour came out
// near-white because it was not $fogcolor, and the coverage varied because it
// was not $alpha either.  hl2_water 0 looked right the entire time for the one
// reason that matters here: mode 0 emits no program at all, so it takes the
// legacy path where colourgen always runs.
//
// Same trap as Patch 132's `#CHROME` (see engine/gl/model_hl.h): a generated
// shader asking for a gen that nothing was ever going to compute.  It costs one
// CPU pass over the vertices and it is what makes the mode work at all.

"#include \"sys/defs.h\"\n"
"#include \"sys/fog.h\"\n"

"varying vec2 tex_c;\n"
"varying vec4 vc;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"tex_c = v_texcoord;\n"
"vc = v_colour;\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"

// The 2x2 Bayer cell, [[0,2],[3,1]], written as arithmetic rather than as an
// array: GLSL 1.10 does not guarantee dynamic indexing of arrays in a fragment
// shader, and this has to run on whatever the driver is.
"float b2 (float x, float y)\n"
"{\n"
"return mod(2.0*x + 3.0*y, 4.0);\n"
"}\n"

// The standard 4x4 from the recursion M2n = [[4Mn, 4Mn+2],[4Mn+3, 4Mn+1]],
// returned as a threshold in (0,1).
"float bayer4 (vec2 p)\n"
"{\n"
"float lo = b2(mod(p.x, 2.0), mod(p.y, 2.0));\n"
"float hi = b2(mod(floor(p.x*0.5), 2.0), mod(floor(p.y*0.5), 2.0));\n"
"return (4.0*lo + hi + 0.5) * (1.0/16.0);\n"
"}\n"

"void main ()\n"
"{\n"
// s_flat is the pass's own map -- $whiteimage for water (so the colour is
// entirely $fogcolor) and the real base texture for glass, which has a frame
// and a pattern worth keeping.
"vec4 col = texture2D(s_flat, tex_c) * vc;\n"

// Screen space, deliberately: a dither locked to the surface's own UVs
// swims and moires as you move.  gl_FragCoord makes the pattern stand
// still on the screen, which is what reads as a stipple rather than as a
// broken texture.
"if (col.a < bayer4(gl_FragCoord.xy))\n"
"discard;\n"

"gl_FragColor = fog4(vec4(col.rgb, 1.0));\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/animated",
"!!ver 130-450\n"
"!!permu FOG\n"
"!!permu LIGHTSTYLED\n"
"!!permu NOFOG\n"
"!!samps anim:2DArray=0\n"

"!!samps !UNLIT lightmap\n"
"!!samps !UNLIT =LIGHTSTYLED lightmap1 lightmap2 lightmap3\n"

// ftesurf (P195): the AnimatedTexture proxy -- a flipbook whose frames all live
// in ONE VTF.  3,342 materials across 741 maps drive one, and every one of them
// has always rendered as frame 0, because img_vtf.c read
// `frames = 1;//vtf->numframes;`.
//
// WHY THIS IS ITS OWN SHADER rather than a permutation of vmt/lightmapped.
// Sampling a flipbook needs sampler2DArray, and that needs GLSL 130; the four
// vmt shaders are `!!ver 110` and raising them would move every permutation of
// every Source material onto a newer context to serve one feature.  A separate
// file is selected per material by mat_vmt.c, exactly the way vmt/transition is,
// so a map with no animated materials compiles none of this.
//
// THE FRAME COUNT is read from the texture with textureSize rather than passed
// in as a define, so no permutation is spent per frame count and the plugin does
// not have to open the VTF to write the shader.  Same idiom as the engine's own
// default2danim.glsl, which is the shipped precedent for an array sampler here.
//
// The frames of one mip level are contiguous in a VTF, which is exactly the
// PTI_2D_ARRAY layout, so the loader change is a reinterpretation and not a
// decode.  It is opt-in on IF_TEXTYPE_2D_ARRAY, which the shader script spells
// `map "$2darray:name"` -- so this shader asking is what makes the frames appear.
//
// Deliberately NARROW: no cubemaps, no bumpmapping, no fake shadows.  A flipbook
// is smoke, fire, a screen or water, and none of those want an envmap.  Keeping
// the permutation set small is also what keeps this from being a second copy of
// vmt/lightmapped that has to be maintained beside it.
//
// #UNLIT, and why this shader cannot just always sample the lightmap.
// UnlitGeneric is 456 of the 927 materials a `hl2_animated 1` actually reroutes
// -- 49% of them -- and mat_vmt.c's own UnlitGeneric arm (:1979) emits a plain
// PASS with no program and no lightmap, because unlit means unlit.  Sampling one
// here would not merely be wasted work: `!!samps lightmap` sets
// prog->defaulttextures |= S_LIGHTMAP0, Shader_Finish then sets
// SHADER_HASLIGHTMAP, and Mod_LightmapAllocSurf gates on exactly that -- so the
// surface is GIVEN a real lightmap page with the map's real lighting in it, and
// every animated sign, screen and light panel in the library would be multiplied
// by the room's shadows and go dark.  It would have looked like the flipbook was
// "too dim" rather than like a lighting bug.
//
// So the lightmap is permutation-gated at the DECLARATION with `!UNLIT`
// (gl_shader.c:2137-2143 -- a leading '!' means "only when this permutation is
// not set"), not merely skipped in the fragment: that is what keeps
// SHADER_HASLIGHTMAP off and stops the page being allocated at all.

"#include \"sys/defs.h\"\n"

"#ifndef ANIMRATE\n"
"#define ANIMRATE 10.0\n"
"#endif\n"

"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"

"#ifndef SCROLL\n"
"#define SCROLL 0.0,0.0\n"
"#endif\n"

"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"

"varying vec2 tex_c;\n"

"#ifndef UNLIT\n"
"varying vec2 lm0;\n"
"#ifdef LIGHTSTYLED\n"
"varying vec2 lm1, lm2, lm3;\n"
"#endif\n"
"#endif\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"#ifndef UNLIT\n"
"lm0 = v_lmcoord;\n"
"#ifdef LIGHTSTYLED\n"
"lm1 = v_lmcoord2;\n"
"lm2 = v_lmcoord3;\n"
"lm3 = v_lmcoord4;\n"
"#endif\n"
"#endif\n"
"tex_c = v_texcoord + e_time * vec2(SCROLL);\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"

"#ifndef UNLIT\n"
"#ifdef LIGHTSTYLED\n"
"#define LIGHTMAP0 texture2D(s_lightmap0, lm0).rgb\n"
"#define LIGHTMAP1 texture2D(s_lightmap1, lm1).rgb\n"
"#define LIGHTMAP2 texture2D(s_lightmap2, lm2).rgb\n"
"#define LIGHTMAP3 texture2D(s_lightmap3, lm3).rgb\n"
"#else\n"
"#define LIGHTMAP texture2D(s_lightmap, lm0).rgb\n"
"#endif\n"

"vec3 lightmap_fragment()\n"
"{\n"
"vec3 lightmaps;\n"
"#ifdef LIGHTSTYLED\n"
"lightmaps  = LIGHTMAP0 * e_lmscale[0].rgb;\n"
"lightmaps += LIGHTMAP1 * e_lmscale[1].rgb;\n"
"lightmaps += LIGHTMAP2 * e_lmscale[2].rgb;\n"
"lightmaps += LIGHTMAP3 * e_lmscale[3].rgb;\n"
"#else\n"
"lightmaps  = LIGHTMAP * e_lmscale.rgb;\n"
"#endif\n"
"return lightmaps;\n"
"}\n"
"#endif\n"

"void main (void)\n"
"{\n"
"vec4 diffuse_f;\n"

// which frame.  sz.z is the layer count, so the modulo keeps the index
// inside [0, frames) and the flipbook wraps on its own without the CPU
// having to know how long the loop is.
"ivec3 sz = textureSize(s_anim, 0);\n"
"float layer = mod(e_time * float(ANIMRATE), float(sz.z));\n"

"diffuse_f = texture2D(s_anim, vec3(tex_c, layer));\n"
"diffuse_f.rgb *= e_colourident.rgb * vec3(COLOR);\n"

"#ifdef MASKLT\n"
"if (diffuse_f.a < float(MASK))\n"
"discard;\n"
"#endif\n"

"#ifndef UNLIT\n"
"diffuse_f.rgb *= lightmap_fragment();\n"
"#endif\n"
"diffuse_f.a *= float(ALPHA);\n"

"#ifdef NOFOG\n"
"gl_FragColor = diffuse_f;\n"
"#else\n"
"gl_FragColor = fog4(diffuse_f);\n"
"#endif\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/emissive",
"!!ver 110\n"
"!!permu FOG\n"
"!!samps diffuse lower fullbright\n"

// ftesurf (P250): Source's $emissiveblend pass -- a self-illumination layer whose
// lookup is displaced by a flow map and then scrolled, which is what makes a rune
// circle appear to churn rather than merely slide.
//
// This is emissive_scroll_blended_pass_ps20b.fxc:31-48 exactly:
//
//     float4 cBaseColor  = tex2D( g_tBaseSampler,     i.vTexCoord0.xy );
//     float4 vFlowValue  = tex2D( g_tFlowSampler,     i.vTexCoord0.xy );
//     float2 vEmissiveTexCoord = vFlowValue.xy + ( g_vEmissiveScrollVector.xy * g_flTime );
//     float4 cEmissiveColor = tex2D( g_tSelfIllumSampler, vEmissiveTexCoord.xy );
//     result.rgb = cBaseColor.rgb * cEmissiveColor.rgb * g_cSelfIllumTint.rgb;
//     result.rgb *= g_flBlendStrength;
//     result.a = 0.0f;
//
// Note the flow map REPLACES the texture coordinate rather than offsetting it --
// vFlowValue.xy, not i.vTexCoord0.xy + vFlowValue.xy.  It is a lookup table into
// the emissive texture, not a perturbation of the surface's own UV, so the
// emissive texture is sampled in the flow map's space and the surface's own
// mapping does not tile it.  Getting that backwards is a plausible-looking
// mistake that produces a plausible-looking result, so it is written down.
//
// alpha 0 with blendFunc add is Source's own choice (the comment there reads "so
// it doesn't change dest alpha"); mat_vmt.c forces st->additive for this arm, so
// the progblendfunc in the shared tail supplies the ONE ONE.

// s_diffuse  = $emissiveblendbasetexture -- the shape, e.g. the circle artwork
// s_lower    = $emissiveblendflowtexture -- the dudv/flow lookup
// s_fullbright = $emissiveblendtexture   -- the thing that scrolls through it

"#include \"sys/defs.h\"\n"
"#include \"sys/fog.h\"\n"

"#ifndef SCROLL\n"
"#define SCROLL 0.11,0.124 // kDefaultEmissiveScrollVector\n"
"#endif\n"

"#ifndef TINT\n"
"#define TINT 1.0,1.0,1.0 // kDefaultEmissiveTint. Not clamped: [10 0 0] is authored.\n"
"#endif\n"

"#ifndef STRENGTH\n"
"#define STRENGTH 1.0  // kDefaultEmissiveBlendStrength\n"
"#endif\n"

"varying vec2 tex_c;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"tex_c = v_texcoord;\n"
"gl_Position = ftetransform();\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"void main ()\n"
"{\n"
"vec4 base_f = texture2D(s_diffuse, tex_c);\n"
"vec4 flow_f = texture2D(s_lower, tex_c);\n"

"vec2 emis_c = flow_f.xy + vec2(SCROLL) * e_time;\n"
"vec4 emis_f = texture2D(s_fullbright, emis_c);\n"

"vec4 result;\n"
"result.rgb = base_f.rgb * emis_f.rgb * vec3(TINT) * float(STRENGTH);\n"
"result.a = 0.0;\n"

"gl_FragColor = fog4additive(result);\n"
"}\n"
"#endif\n"
},
#endif
#ifdef GLQUAKE
{QR_OPENGL, 110, "vmt/imposter",
"!!ver 110\n"
"!!permu FOG\n"
"!!samps reflectcube\n"

"#include \"sys/defs.h\"\n"

//FTESurf Patch 263: Source's WindowImposter.
//
//A brush/displacement shader that draws ONE thing -- its $envmap cubemap,
//sampled by the VIEW DIRECTION -- and nothing else.  No basetexture, no
//lightmap, no lighting.  What separates it from every other envmap in this
//directory is one sentence of Valve's documentation: the face's orientation is
//not taken into account when reflecting the cubemap, which makes it convenient
//for windows and doors that hide what is behind them while looking like they do
//not -- and for faking more than one simultaneous skybox.
//
//So the single line that IS this shader is that the sample direction is the view
//ray itself and not reflect(view, normal).  Reflecting off the surface normal --
//which is what lightmapped.glsl and vertexlit.glsl correctly do for a real
//$envmap -- would make the pane behave like a mirror: the image would slide the
//wrong way as the camera moves, and a flat ceiling would smear one cubemap texel
//across the whole face.  Sampling the view ray makes the surface behave like a
//window onto a cube, which is exactly a second skybox.
//
//WHY THIS EXISTS: surf_monolith's bonus 4 is roofed and walled by a 2-unit slab
//of materials/fakeskies/mpa45.vmt, laid 4 units UNDER the map's real sky brush,
//so the room shows a red sky while the rest of the map shows sky138a.  With no
//WindowImposter arm in the parser that material fell through to vmt/unlit, whose
//diffusemap resolved to the cubemap file itself -- img_vtf.c loads it as
//PTI_CUBE, not a 2D base -- so the backend substituted missing_texture and the
//whole room drew as the notexture checkerboard.  155 materials, 59 maps.
//
//WORLD SPACE, computed straight from the position rather than through the
//tangent basis.  e_eyepos is the eye in MODEL space, so v_position - e_eyepos is
//a model-space direction and m_model takes it to world -- the same space
//lightmapped.glsl's cube_c ends up in, so a cubemap looks identical whichever
//material samples it.  Going via mat3(v_svector, v_tvector, v_normal) the way
//that shader does would be equivalent for an orthonormal basis and would need
//three vertex attributes this shader has no other use for; the direct form needs
//only v_position, which every surface has.
//
//Not normalised: textureCube takes a direction of any length.
//
//NOTE FOR THE NEXT PERSON ADDING A FILE HERE: plugins/hl2/Makefile carries a
//hand-maintained VMTPROGSBASE list, and a .glsl that is not in it is silently
//left out of the DLL while make reports success.  This file cost one build to
//rediscover that.  Essays go in // comments, never /* */: generatebuiltinsl
//passes // lines through as C comments but turns everything else into string
//literals, so a quotation mark inside a block comment breaks the generated
//header.  That cost the second build.

"varying vec3 cubedir;\n"

"#ifdef VERTEX_SHADER\n"
"void main ()\n"
"{\n"
"gl_Position = ftetransform();\n"
"cubedir = (m_model * vec4(v_position.xyz - e_eyepos, 0.0)).xyz;\n"
"}\n"
"#endif\n"

"#ifdef FRAGMENT_SHADER\n"
"#include \"sys/fog.h\"\n"

//$alpha and $color, which first-party Source does not accept on this shader and
//which the library uses anyway.  Censused over all 155 WindowImposter materials:
//$envmap 155 (100%), $nofog 150, $color 25, $alpha 22, $ignorez 18, $nocull 6.
//So roughly 30% of them say something about tint or opacity, and a version of
//this shader that ignored both would draw those at the wrong colour while
//looking like it worked.
//
//Both arrive through the generic progargs the parser has already built -- they
//are value defines rather than permutations, so they need no !!permu and an
//unused one costs nothing.  $ignorez and $nocull need nothing here either: the
//shared tail in mat_vmt.c emits nodepth and cull disable for them.
//
//Opaque by default: hiding what is behind it is the entire point of an imposter,
//and a blended one would have to sort.
"#ifndef ALPHA\n"
"#define ALPHA 1.0\n"
"#endif\n"

"#ifndef COLOR\n"
"#define COLOR 1.0,1.0,1.0\n"
"#endif\n"

"void main ()\n"
"{\n"
"vec4 imposter_f = vec4(textureCube(s_reflectcube, cubedir).rgb, float(ALPHA));\n"
"imposter_f.rgb *= vec3(COLOR);\n"
"gl_FragColor = fog4( imposter_f );\n"
"}\n"
"#endif\n"
},
#endif
